### ISSUE TITLE
change pics folder structure

### ISSUE THREAD

**Issue by SDSTony** [Pseudo-Lab/Tutorial-Book#36]
이미지 폴더 구조 변경
방법 A. 하나의 폴더 내 CV-ch1-img01 , TS-ch1-img01 식으로 구분
방법 B. CV폴더, TS폳더 여러개 만들어서 각각 폴더내 ch1-img01, ch1-img02 식으로 구분

**Comment by hwaneest** [comment]
의견 남깁니다. (성진님 혼자 고민하시지 않기를 바라는 마음에~!)
(표기 : [OD] Object Detection / [TS] Time Series / [GAN] GAN )

몇 가지 측면에서 **방법.A**가 낫다고 생각하는데요,
- 하나의 주제 당 이미지 개수가 OD는 4개 정도, TS는 9개 정도로 많지 않음 (GAN은 송구하게도 저때문에 개수가 많아지고 있긴 한데...)
- 폴더 depth가 늘어나는 것을 지양 (향후 코드 편의성, 과거 수정 필요성 없음, 기타 "simplify" 간단함이 좋다는 생각)
- 주제 개수가 많아질 것 같지 않음 (2기까지 완료하면 총 4개 주제) >> 방법B로 이미지를 폴더링하게 되면 폴더가 4개+3기갯수... 정도 될 듯. (주제가 제한적) >> 비효율로 사료됨

개인적인 의견입니다~!ㅎㅎ

**Comment by hwaneest** [comment]
+) 아 요거 OD 때 거는 네이밍 컨벤션 통일 안 되어 있더라구요. 변경하는 것 잊지 않기로 노티입니다~

**Comment by SDSTony** [comment]
> 의견 남깁니다. (성진님 혼자 고민하시지 않기를 바라는 마음에~!)
> (표기 : [OD] Object Detection / [TS] Time Series / [GAN] GAN )
> 
> 몇 가지 측면에서 **방법.A**가 낫다고 생각하는데요,
> 
> * 하나의 주제 당 이미지 개수가 OD는 4개 정도, TS는 9개 정도로 많지 않음 (GAN은 송구하게도 저때문에 개수가 많아지고 있긴 한데...)
> * 폴더 depth가 늘어나는 것을 지양 (향후 코드 편의성, 과거 수정 필요성 없음, 기타 "simplify" 간단함이 좋다는 생각)
> * 주제 개수가 많아질 것 같지 않음 (2기까지 완료하면 총 4개 주제) >> 방법B로 이미지를 폴더링하게 되면 폴더가 4개+3기갯수... 정도 될 듯. (주제가 제한적) >> 비효율로 사료됨
> 
> 개인적인 의견입니다~!ㅎㅎ

감사합니다 폴더 depth가 늘어나면 이미지 참조할 때 불편하긴 하죠 ㅎㅎ
