### ISSUE TITLE
GAN ch1 1차 수정안

### ISSUE THREAD

**Issue by elibooklover** [Pseudo-Lab/Tutorial-Book#55]

**Comment by elibooklover** [comment]
- 오타수정: FIS --> FID

**Comment by hwaneest** [comment]
호열님 상세한 확인 감사드립니다. 이전 이슈에 포함되어 있던 내용으로 수정은 하였고 PR전이라 아직 반영이 안 되어 있습니다.
티켓 클로즈하겠습니다. 감사합니다!
