### ISSUE TITLE
GAN ch2 수정거리 (from 동환 to 성진님)

### ISSUE THREAD

**Issue by hwaneest** [Pseudo-Lab/Tutorial-Book#56]
안녕하세요 성진님, 수정할 만한 사항들을 적어보았습니다 :) 

- 첫마디 수정 : 이전 장에서는 GAN ~ 알아보았습니다.
   -> 이전 장에서는 GAN의 개념과 모델, 평가지표 등에 대해 알아보았습니다.
- 어구 수정
  1) [2번째 문단] 해당 모델을 ~ 데이터 입니다.
     -> 2개 문장이 길이가 길어서 하나로 합치는 건 어떨지요?
     -> 해당 모델을 구축하기 위해 활용할 데이터셋은 Vic...400 라는 데이터로,
          19세기 그림들의 흑백/컬러 쌍으로 이루어진 데이터입니다.
  2) [마지막 문단] 지금까지 ~ 확인했습니다.
     -> 지금까지 Victorian400 데이터셋에 저장된 이미지를 시각화 해보았습니다.

전반적으로 무난히 흐름대로 잘 읽혔습니다. 의견 드립니다~!

**Comment by SDSTony** [comment]
해당 모델을 구축하기 위해 활용할 데이터셋은 Victorian400 입니다. 19세기 그림들의 흑백 / 컬러 쌍으로 이뤄진 데이터 입니다. 
-> 한 문장

**Comment by hwaneest** [comment]
티켓정리. 캡처하여 #50 에 남겨두었습니다.
