### ISSUE TITLE
GAN ch4 수정거리 (from 동환 to 호열님)

### ISSUE THREAD

**Issue by hwaneest** [Pseudo-Lab/Tutorial-Book#59]
안녕하세요 호열님, 수정할 만한 사항들을 적어보았습니다 :)

거의 없는 것 같은데.. 한 가지 그냥 보면서 느낀 점은 호흡이 긴 부분이 어쩔 수 없는 것일지 였습니다. 혹시 class와 udf가 여러개가 들어가 있는 하나의 긴 셀을 2개 이상으로 나누게 되면 흐름상 어색할지요? 

제가 U-NET을 직접 짜본 경험이 없어서 판단에 맡깁니다.
코딩을 조금이라도 보거나 해본 사람이라면 이해할 수 있을 것 같습니다.
의견 드립니다~!

**Comment by SDSTony** [comment]
![Uploading image.png…]()

**Comment by SDSTony** [comment]
![image](https://user-images.githubusercontent.com/46511987/106614574-db20b200-65ae-11eb-909e-6d93572559a7.png)

**Comment by hwaneest** [comment]
티켓정리. #53 에 캡처로 남겨두었습니다.
